import random

name = "hamza"

lower = "abcdefghijklmnopqrstuvwxyz"
upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
numbers = "0123456789"
symbols = "!@#$%^&*()_-+=?><["

use_lower = input("Include lowercase letters? (y/n): ").strip().lower() == 'y'
use_upper = input("Include uppercase letters? (y/n): ").strip().lower() == 'y'
use_numbers = input("Include numbers? (y/n): ").strip().lower() == 'y'
use_symbols = input("Include symbols? (y/n): ").strip().lower() == 'y'

min_lower = 0
min_upper = 0

if use_lower:
    min_lower = int(input("Minimum lowercase letters (0 for none): "))
if use_upper:
    min_upper = int(input("Minimum uppercase letters (0 for none): "))

all_chars = ""
if use_lower:
    all_chars += lower
if use_upper:
    all_chars += upper
if use_numbers:
    all_chars += numbers
if use_symbols:
    all_chars += symbols

if not all_chars:
    print("You must select at least one character type!")
else:
    length = int(input("Enter a length: "))
    
    if min_lower + min_upper > length:
        print("Error: The sum of minimum lowercase and uppercase letters exceeds the password length!")
    else:
        password = (
            random.sample(lower, min_lower) +
            random.sample(upper, min_upper) +
            random.sample(all_chars, length - (min_lower + min_upper))
        )
        random.shuffle(password)
        password = ''.join(password)

        if length < 8 or (password.isalpha() or password.isdigit()):
            strength = "Weak"
        elif length < 12 or (not any(char in symbols for char in password)):
            strength = "Moderate"
        else:
            strength = "Strong"

        print("\nGenerated Password:", password)
        print("Length of Password:", len(password))
        print("Password Strength:", strength)
        print("Generated by:", name)
 
